baseurl: 'https://cradletograver.com/'
languageCode: en-us
defaultContentLanguage: en
theme: hugo-w3-simple
disqusShortname: https-cradletograver-com
googleAnalytics: 'G-KK38GDVNEW'
paginate: 12
hasCJKLanguage: true
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown
  - _files$
  - _cache$
markup:
  goldmark:
    renderer:
      unsafe: true
languages:
  en:
    weight: 0
    languageName: English
    contentDir: content/english
    params:
      title: Cradle To Grave R
      authorinfo: <h4>Authored By Mark gingrass</h4>
      licenseinfo: >-
        <p class="w3-small">Mark Gingrass, a good man living on the earth,
        loving making website with hugo. This article is licensed under a <a
        rel="license" href="https://creativecommons.org/licenses/by/4.0/"
        class="w3-text-white">Creative Commons Attribution 4.0 International
        License</a>.</p>
      logotext: Cradle to Grave R
      isso_baseurl: ''
      isso_langcode: en
      cookie_info: >-
        This website uses cookies to ensure you get the best experience on our
        website. [Learn more](/privacy-policy/)
    menu:
      main:
        - name: About
          url: /about/
          weight: 2
        - name: Categories
          url: /categories/
          weight: 3
        - name: Tags
          url: /tags/
          weight: 4
        - name: All Posts
          url: /allposts/
          weight: 5
  zh-cn:
    weight: 10
    languageName: Chinese
    contentDir: content/chinese
    params:
      title: 王一贴的博客
      authorinfo: <h4>本文由王一贴原创</h4>
      licenseinfo: >-
        <p class="w3-small">王一贴，曾记录于《红楼梦》第八十回人物。任何问题，一贴搞定.<br>本文采用<a
        rel="license" href="http://creativecommons.org/licenses/by/4.0/"
        class="w3-text-white">知识共享署名 4.0 国际许可协议</a>进行许可。</p>
      logotext: 王一贴的博客
      isso_baseurl: ''
      isso_langcode: zh
    menu:
      main:
        - name: 关于
          url: /zh-cn/about/
          weight: 2
        - name: 分类
          url: /zh-cn/categories/
          weight: 3
        - name: 标签
          url: /zh-cn/tags/
          weight: 4
        - name: 全部帖子
          url: /zh-cn/allposts/
          weight: 5
        - name: English
          url: /
          weight: 6
params:
  welcomemessage: false
  authorandlicense: false
  authorimgurl: ''
  relatedPosts: true
  backtotop: true
  lazyload: true
  glowlogo: true
  scrollindicator: true
  allliststyle: false
  gridstyle: true
  readingtime: true
  firstpic: true
  socialshare: true
  socialicon: true
  googletranslate: true
  searchfunction: true
  description: 'All things R. Tutorials, tips, videos, blogs.'
  onesignalid: ''
  allowads: true
  logotext: Cradle to Grave R
  footer: >-
    &copy; [Mark Gingrass](https://markgingrass.com) 2020 |
    [Github](https://github.com/mtgingrass/CradleToGraveR-W3-simple) |
    [Twitter](https://twitter.com/markgingrass)  | [RSS](/index.xml)
  social:
    b-stack-overflow: 'https://stackoverflow.com/users/6855770/devgin'
    c-twitter: 'https://twitter.com/markgingrass'
    d-facebook: 'https://www.facebook.com/mark.gingrass.1'
    e-github: 'https://github.com/mtgingrass'
    f-youtube: 'https://www.youtube.com/c/CradleToGraveR'
    g-linkedin: 'https://www.linkedin.com/in/markgingrass/'
